name: Deploy Docs to GihHub Pages

on:
  push:
    branches: [ "{{ cookiecutter.release_branches | replace(' ', '') | replace(',', '\", \"') }}" ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_{{ cookiecutter.project_upper }}_DOCS=ON -DBUILD_{{ cookiecutter.project_upper }}=OFF

      - name: Build docs
        run: cmake --build build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/docs/html

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ '{{ steps.deployment.outputs.page_url }}' }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
